### ISSUE TITLE
How to generate a synthesis image in capacity abuse attack?

### ISSUE THREAD

**Issue by peiyangL** [csong27/ml-model-remember#1]
Hi, May I have a question that what's the special meaning of line 177~123 in https://github.com/csong27/ml-model-remember/blob/9893a48478b878fadd994f7c2cdfa5377e93fccf/attack.py
thank you :)

**Comment by csong27** [comment]
This snippet just naively set two pixels of the synthesized image with some deterministic value based on data index to make sure the synthesized images are not duplicated. The synthesized images are very sparse. You can use other ways such as random sampling with a manual seed.

**Comment by peiyangL** [comment]
Thanks for you response!
