### ISSUE TITLE
Details of synthetic text in black-box attack setting

### ISSUE THREAD

**Issue by Alice47962** [csong27/ml-model-remember#2]
the paper said that the synthetic text can be generated in the following way

> GenData can enumerate all singleton tokens in lexicographic order, then all pairs of tokens in lexicographic order, and so on until the list is as long as the number of synthetic documents needed

For a given vocabulary like this "1 : the, 2 : and, 3 : a, 4 : of, 5 : to, 6 : is, 7 : this, 8 : in, 9 : it, 10 : i......", is that means a synthetic document can be "the and a of to is this in it i"?

And if I need 10 synthetic documents. What are the differences between the 10 documents? Could you show me an example of different synthetic documents, or the code for synthesizing text.

Thank you~

**Comment by csong27** [comment]
Hi,
For your example, the first 10 synthetic texts are each single word, e.g. word "the" as a document.
Then we can enumerate combinations of pairs "the and", "the a". If all pairs are enumerated, we go on to triples "the and a", "the and of" so on.

**Comment by Alice47962** [comment]
ok, I got it.
Thank you~
